name: Python Unittest CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: check out the code from the repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Install project
              run: pip install -e .
            
            - name: Run tests
              run: pytest
            
            - name: Build and Push Docker Image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                image: prithvirajsawant/git-actions-demo
                registry: docker.io
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}